<!DOCTYPE html>
<html><head><title>Throws</title><link rel="stylesheet" href="../../styles.css"/><script src="../../scripts.js"></script></head><body onload="ro();">
<div class="rH">7 references to Throws</div><div class="rA">UniRx.Tests (7)</div><div class="rG" id="UniRx.Tests"><div class="rF"><div class="rN">AggregateTest.cs (1)</div>
<a href="../AggregateTest.cs.html#24"><b>24</b>AssertEx.<i>Throws</i>&lt;InvalidOperationException&gt;(() =&gt; Observable.Empty&lt;int&gt;().Aggregate((x, y) =&gt; x + y).Wait());</a>
</div>
<div class="rF"><div class="rN">Observable.PagingTest.cs (1)</div>
<a href="../Observable.PagingTest.cs.html#839"><b>839</b>AssertEx.<i>Throws</i>&lt;ArgumentOutOfRangeException&gt;(() =&gt; range.Skip(-1));</a>
</div>
<div class="rF"><div class="rN">RangeTest.cs (1)</div>
<a href="../RangeTest.cs.html#12"><b>12</b>AssertEx.<i>Throws</i>&lt;ArgumentOutOfRangeException&gt;(() =&gt; Observable.Range(1, -1).ToArray().Wait());</a>
</div>
<div class="rF"><div class="rN">SubjectTest.cs (3)</div>
<a href="../SubjectTest.cs.html#151"><b>151</b>AssertEx.<i>Throws</i>&lt;ObjectDisposedException&gt;(() =&gt; subject.OnNext(0));</a>
<a href="../SubjectTest.cs.html#152"><b>152</b>AssertEx.<i>Throws</i>&lt;ObjectDisposedException&gt;(() =&gt; subject.OnError(new Exception()));</a>
<a href="../SubjectTest.cs.html#153"><b>153</b>AssertEx.<i>Throws</i>&lt;ObjectDisposedException&gt;(() =&gt; subject.OnCompleted());</a>
</div>
<div class="rF"><div class="rN">TakeTest.cs (1)</div>
<a href="../TakeTest.cs.html#14"><b>14</b>AssertEx.<i>Throws</i>&lt;ArgumentOutOfRangeException&gt;(() =&gt; range.Take(-1));</a>
</div>
</div>
</body></html>